name: Reranker Model Tests

on:
  push:
    branches: [ main, reranking-implementation ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM

jobs:
  reranker-testing:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync
        
    - name: Start Ollama Server
      run: |
        # Download and start Ollama with new engine
        curl -fsSL https://ollama.ai/install.sh | sh
        OLLAMA_NEW_ENGINE=1 ollama serve &
        sleep 10
        
    - name: Setup Test Models  
      run: |
        # Pull test models for Ollama
        ollama pull bge-v2-m3 || echo "Model not available, skipping"
        ollama pull qwen3-0.6b || echo "Model not available, skipping"
        
    - name: Run Official Implementation Tests
      run: |
        # Test official implementations (HuggingFace models)
        uv run python test_reranker.py --implementation official
        
    - name: Run Ollama Implementation Tests
      run: |
        # Test Ollama implementations
        uv run python test_reranker.py --implementation ollama
        
    - name: Generate Summary Report
      run: |
        # Generate comparison report if script exists
        if [ -f "compare_results.py" ]; then
          uv run python compare_results.py
        fi
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: reranker-test-results
        path: |
          results/
          *.md
